### ISSUE TITLE
NetEase NeoX

### ISSUE THREAD

**Issue by yretenai** [SteamDatabase/FileDetectionRuleSets#117]
### Some reference to the engine, such as the developer site or a wikipedia article.

NetEase Proprietary Engine.

Only mentioned in passing describing EVE Echoes in press releases.

https://www.neteasegames.com/news/game/20191113/30576_848390.html
https://www.neteasegames.com/news/game/20190807/30576_826962.html

### SteamDB links

- https://steamdb.info/app/1755920/
- https://steamdb.info/app/1368910/
- https://steamdb.info/app/551170/

### Possible way to detect it

any of (optionally)

- npk.dll
- nxmalloc.dll
- nxapp.dll
- nxasset.dll
- nxcore.dll

always has at least one file that has an `.npk` extension.

**Comment by Lifeismana** [comment]
Each of the dll that you listed are only used in one depot (app) or 2, so it's not worth it to search for them.

Looking a bit deeper into these .npk files each game that you listed have a `script.npk` file, it might be the file we should look for
Can you check this list for false positive game, that you know aren't using this engine ?

* [Sonicomi](https://steamdb.info/app/444140/)
* [Onmyoji](https://steamdb.info/app/551170/)
* [Song of Saya](https://steamdb.info/app/702050/)
* [Crusaders of Light](https://steamdb.info/app/775220/)
* [Rules Of Survival](https://steamdb.info/app/788260/depots/)
* [光明大陆](https://steamdb.info/app/793950/)
* [sweet pool](https://steamdb.info/app/852910/)
* [CreativeDestruction](https://steamdb.info/app/893520/depots/)
* [Togainu no Chi](https://steamdb.info/app/1174400/)
* [Cyber Hunter](https://steamdb.info/app/1209040/)
* [YOU and ME and HER](https://steamdb.info/app/1293820/)
* [Super Mecha Champions](https://steamdb.info/app/1368910/)
* [Dramatical Murder](https://steamdb.info/app/1481080/)
* [Infinite Lagrange](https://steamdb.info/app/1755920/)

**Comment by yretenai** [comment]
It seems NitroPlus used the same extension for their engine MWARE.

##  NetEase NeoX NPK

- [Onmyoji](https://steamdb.info/app/551170/)
- [Crusaders of Light](https://steamdb.info/app/775220/)
- [Rules Of Survival](https://steamdb.info/app/788260/depots/)
- [光明大陆](https://steamdb.info/app/793950/)
- [CreativeDestruction](https://steamdb.info/app/893520/depots/)
 - [Cyber Hunter](https://steamdb.info/app/1209040/)
 - [Super Mecha Champions](https://steamdb.info/app/1368910/)
 - [Infinite Lagrange](https://steamdb.info/app/1755920/)

## NitroPlus MWARE NPK

- [Sonicomi](https://steamdb.info/app/444140/)
 - [Song of Saya](https://steamdb.info/app/702050/)
 - [sweet pool](https://steamdb.info/app/852910/)
- [YOU and ME and HER](https://steamdb.info/app/1293820/)
- [Dramatical Murder](https://steamdb.info/app/1481080/)
 - [Togainu no Chi](https://steamdb.info/app/1174400/)

Too many false positives.
