### ISSUE TITLE
The Witcher: Enhanced Edition detected as using Unity engine

### ISSUE THREAD

**Issue by XJDHDR** [SteamDatabase/FileDetectionRuleSets#156]
### SteamDB link to the game

https://steamdb.info/app/20900/info/

### What is it being detected as and what should it be detected as? Any other information?

SteamDB currently has the following under Detected Technologies: Engine.Aurora, Engine.Unity, SDK.Bink_Video

Engine.Aurora and SDK.Bink_Video are correct. However, this game doesn't use Unity and so, this tag is not supposed to be there.

**Comment by xPaw** [comment]
It's detecting the digital comic: `Digital Comic/DigitalComic_Data/Managed/UnityEngine.dll`, so as far as the detector is concerned it's "correct". We don't have manual (un)tagging.
