### ISSUE TITLE
Warface doesn't have it's engine detected

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#168]
### SteamDB link to the game

https://steamdb.info/app/291480/

### What should it be detected as?

CryEngine

**Comment by xPaw** [comment]
https://steamdb.info/depot/291481/ because it's just a launcher without game content on Steam?

**Comment by diedyesterdaywashere** [comment]
> https://steamdb.info/depot/291481/ because it's just a launcher without game content on Steam?

oh, sorry, i just haven't really played warface in steam but i remembered it had cryengine, so thought that it was broken, thanks for responding that fast
