### ISSUE TITLE
Add support for Ubisoft Anvil family detection

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#169]
### Some reference to the engine, such as the developer site or a wikipedia article.

https://en.wikipedia.org/wiki/Ubisoft_Anvil
The engine itself has multiple iterations like idTech.

### SteamDB links

Scimitar
- [Assassin's Creed (2007)](https://steamdb.info/app/15100/)
- [Prince of Persia (2008)](https://steamdb.info/app/19980/)
- [Shaun White Snowboarding (2008)](https://steamdb.info/app/19990/)

Anvil
- [Assassin's Creed II (2009)](https://steamdb.info/app/33230/)
- [Prince of Persia: The Forgotten Sands (2010)](https://steamdb.info/app/33320/)
- [Assassin's Creed: Brotherhood (2010)](https://steamdb.info/app/48190/)
- [Assassin's Creed: Revelations (2011)](https://steamdb.info/app/201870/)

AnvilNext
- [Assassin's Creed III (2012)](https://steamdb.info/app/208480/)
- [Assassin's Creed III: Liberation (2012)](https://steamdb.info/app/260210/)
- [Assassin's Creed IV: Black Flag (2013)](https://steamdb.info/app/242050/)
- [Assassin's Creed IV: Freedom Cry (2013)](https://steamdb.info/app/277590/)
- [Assassin's Creed Rogue (2014)](https://steamdb.info/app/311560/)

AnvilNext 2.0
- [Assassin's Creed Unity (2014)](https://steamdb.info/app/289650/)
- [Assassin's Creed Syndicate (2015)](https://steamdb.info/app/368500/)
- [Tom Clancy's Rainbow Six Siege (2015)](https://steamdb.info/app/359550/)
- [Steep (2016)](https://steamdb.info/app/460920)
- [For Honor (2017)](https://steamdb.info/app/304390/)
- [Tom Clancy's Ghost Recon Wildlands (2017)](https://steamdb.info/app/460930/)
- [Assassin's Creed Origins (2017)](https://steamdb.info/app/582160/)
- [Assassin's Creed Odyssey (2018)](https://steamdb.info/app/812140/)
- [Tom Clancy's Ghost Recon Breakpoint (2019)](https://steamdb.info/app/2231380/)

Ubisoft Anvil
- [Assassin's Creed Valhalla (2020)](https://steamdb.info/app/2208920/)
- [Immortals Fenyx Rising (2020)](https://steamdb.info/app/2221920/)

**Comment by Lifeismana** [comment]
Looking quickly at it, looking for "*.forge" files could work, i'll check later if just looking for that will bring some false positive games

**Comment by diedyesterdaywashere** [comment]
> Looking quickly at it, looking for "*.forge" files could work, i'll check later if just looking for that will bring some false positive games

ok thanks!

**Comment by Lifeismana** [comment]
Here's the list of games that get matched:

https://steamdb.info/app/15100
https://steamdb.info/app/19980
https://steamdb.info/app/19990
https://steamdb.info/app/33230
https://steamdb.info/app/33320
https://steamdb.info/app/34420 (false positive)
https://steamdb.info/app/48190
https://steamdb.info/app/201870
https://steamdb.info/app/208480
https://steamdb.info/app/242050
https://steamdb.info/app/260210
https://steamdb.info/app/277590
https://steamdb.info/app/289650
https://steamdb.info/app/304390
https://steamdb.info/app/311560
https://steamdb.info/app/368500
https://steamdb.info/app/812140
https://steamdb.info/app/911400
https://steamdb.info/app/2208920
https://steamdb.info/app/359550
https://steamdb.info/app/396410
https://steamdb.info/app/460920
https://steamdb.info/app/460930
https://steamdb.info/app/550040
https://steamdb.info/app/584210
https://steamdb.info/app/623990
https://steamdb.info/app/654310
https://steamdb.info/app/582160
https://steamdb.info/app/719690
https://steamdb.info/app/747500
https://steamdb.info/app/768350
https://steamdb.info/app/775430
https://steamdb.info/app/924720
https://steamdb.info/app/2221920
https://steamdb.info/app/2231380

Seems like there's only one false positive and i don't think there's any game missing from the list you gave

**Comment by diedyesterdaywashere** [comment]
@Lifeismana i can try to see whats trigger that false positive, so it does not get triggered if its needed?

**Comment by Lifeismana** [comment]
Looking a bit more into it, one way of fixing that false positive would be by looking directly for:
- datapc.forge
- datapc64.forge (rainbow 6 siege)
- gamedatapc_00.forge (for honor)

Do you want to do the pr ? (or else i'll do it)

**Comment by diedyesterdaywashere** [comment]
> Looking a bit more into it, one way of fixing that false positive would be by looking directly for:
> - datapc.forge
> - datapc64.forge (rainbow 6 siege)
> - gamedatapc_00.forge (for honor)
> 
> Do you want to do the pr ? (or else i'll do it)

don't really know regex stuff so i guess it would be better for you to do it, could you also maybe check other engine stuff when you'll have time? :D

**Comment by Lifeismana** [comment]
okay, but you could try if you want, it's not really hard (using <https://regex101.com/> helps a lot (don't forget to change the delimiter to something else than slash))
yeah, yeah but it's time consuming so don't expect it soon (apply some Valve Time:tm: to it :D)

**Comment by diedyesterdaywashere** [comment]
> okay, but you could try if you want, it's not really hard (using <https://regex101.com/> helps a lot (don't forget to change the delimiter to something else than slash))
> yeah, yeah but it's time consuming so don't expect it soon (apply some Valve Time:tm: to it :D)

yea I'll look into other already made rules to have them as example, so I'll be able to make it myself later
