### ISSUE TITLE
Add Diesel detection

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#175]
### Some reference to the engine, such as the developer site or a wikipedia article.

https://en.wikipedia.org/wiki/Diesel_(game_engine)

### SteamDB links

https://steamdb.info/app/13640/
https://steamdb.info/app/13510/
https://steamdb.info/app/21680/
https://steamdb.info/app/21670/
https://steamdb.info/app/21070/
https://steamdb.info/app/21080/
https://steamdb.info/app/42120/
https://steamdb.info/app/24240/
https://steamdb.info/app/218620/
https://steamdb.info/app/414740/

**Comment by diedyesterdaywashere** [comment]
found dieselx.cfg file in games, i guess it can be identified by that

**Comment by Lifeismana** [comment]
Looking for dieselx.cfg matchs everything except [Tom Clancy's Ghost Recon: Advanced Warfighter](https://steamdb.info/app/13640/depots/) & [
Tom Clancy's Ghost Recon: Advanced Warfighter 2
](https://steamdb.info/app/13510/depots/)

**Comment by diedyesterdaywashere** [comment]
> Looking for dieselx.cfg matchs everything except [Tom Clancy's Ghost Recon: Advanced Warfighter](https://steamdb.info/app/13640/depots/) & [
> Tom Clancy's Ghost Recon: Advanced Warfighter 2
> ](https://steamdb.info/app/13510/depots/)

I'll try to research more stuff in the morning (you can see my time in github), but yeh, thats atleast something

**Comment by diedyesterdaywashere** [comment]
![image](https://user-images.githubusercontent.com/81169193/215270063-aea22e22-cd2c-4efd-be04-7fc72ed98250.png)
.diesel files?

**Comment by diedyesterdaywashere** [comment]
found it in first advanced warfighter

**Comment by diedyesterdaywashere** [comment]
i don't think second game has anything that shows it unfortunately
