### ISSUE TITLE
Add Phaser detection

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#187]
### Some reference to the engine, such as the developer site or a wikipedia article.

Phaser itself is a framework for WebGL but im not sure if there's a way to locate webgl itself so yes
https://en.wikipedia.org/wiki/Phaser_(game_framework)

### SteamDB links

https://steamdb.info/app/1131080/

### Possible way to detect it

assets/lib/phaser

**Comment by MichaelHinrichs** [comment]
Well, we have Phaser detection now. Is anyone going to close this?

**Comment by diedyesterdaywashere** [comment]
> Well, we have Phaser detection now. Is anyone going to close this?

add "closes #187" to ur pr description and it will close automatically when pull request gets accepted
