### ISSUE TITLE
Add Amazon Lumberyard detection

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#190]
### Some reference to the engine, such as the developer site or a wikipedia article.

https://en.wikipedia.org/wiki/Amazon_Lumberyard

### SteamDB links

https://steamdb.info/app/583240/
https://steamdb.info/app/2087030/
https://steamdb.info/app/1063730/

### Possible way to detect it

bootstrap.cfg in root folder present in all 3 games i mentioned, it might be too general tho

**Comment by Lifeismana** [comment]
duplicate of #27
