### ISSUE TITLE
Frostbite False Negative

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#200]
### SteamDB link to the game

https://steamdb.info/app/1222670/

### What should it be detected as?

Engine.Frostbite

**Comment by gibbed** [comment]
Sims 4 is not Frostbite.

**Comment by diedyesterdaywashere** [comment]
> Sims 4 is not Frostbite.

google said it is, lemme check again

**Comment by diedyesterdaywashere** [comment]
> Sims 4 is not Frostbite.

oh, wait, it really is not frostbite, sorry, i am just stupid
