### ISSUE TITLE
Add Liquid Engine Detection

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#202]
### Some reference to the engine, such as the developer site or a wikipedia article.

https://www.moddb.com/engines/liquid/games

### SteamDB links

https://steamdb.info/app/251530/
https://steamdb.info/app/236730/
https://steamdb.info/app/91200/
https://steamdb.info/app/323190/

### Possible way to detect it

i believe PCTouchHelper.dll is only used in 11bit studios games and Liquid Engine is their inhouse engine so...

**Comment by diedyesterdaywashere** [comment]
yo @Lifeismana could you pls test `^PCTouchHelper\.dll$`? because i can't figure out how to run tests

**Comment by Lifeismana** [comment]
Indeed, it could ne a good way of finding it
Here's the list of app that match this:
https://steamdb.info/app/91200/
https://steamdb.info/app/236730/
https://steamdb.info/app/251530/
https://steamdb.info/app/252170/
https://steamdb.info/app/282070/
https://steamdb.info/app/294750/
https://steamdb.info/app/323190/

Doesn't look like there's any false positive so, feel free to do the PR  :D

**Comment by diedyesterdaywashere** [comment]
> Indeed, it could ne a good way of finding it
> Here's the list of app that match this:
> https://steamdb.info/app/91200/
> https://steamdb.info/app/236730/
> https://steamdb.info/app/251530/
> https://steamdb.info/app/252170/
> https://steamdb.info/app/282070/
> https://steamdb.info/app/294750/
> https://steamdb.info/app/323190/
> 
> Doesn't look like there's any false positive so, feel free to do the PR  :D

I'll read contributing.md in the morning to understand what else do i need besides just regex and then I'll make it :D

**Comment by diedyesterdaywashere** [comment]
wait so i need to fork the repo to make changes to it? thought i could just make a branch, but ok

**Comment by Lifeismana** [comment]
you do not have to close the issue before the pr get accepted, mentioning the issue with "closes #issue_nbr" automatically does it

**Comment by diedyesterdaywashere** [comment]
oh ok
