### ISSUE TITLE
Add Vision Engine Detection

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#214]
### Some reference to the engine, such as the developer site or a wikipedia article.

https://en.wikipedia.org/wiki/Vision_(game_engine)

### SteamDB links

- [Desperados 2: Cooper's Revenge](https://steamdb.info/app/9710/)
- [I-Fluid](https://steamdb.info/app/23200/)
- [The Settlers 7: History Edition](https://steamdb.info/app/965320/)
- [ArcaniA](https://steamdb.info/app/39690/)
- [Stronghold 3](https://steamdb.info/app/47400/)
- [Orcs Must Die!](https://steamdb.info/app/102600/)
- [World of Subways 3 – London Underground Circle Line](https://steamdb.info/app/283620/)
- [Bus-Simulator 2012](https://steamdb.info/app/253770/)
- [Orcs Must Die! 2](https://steamdb.info/app/201790/)
- [Dogfight 1942](https://steamdb.info/app/217790/)
- [Munich Bus Simulator: ](https://steamdb.info/app/283560/)
- [DARK](https://steamdb.info/app/225360/)
- [Pressure](https://steamdb.info/app/224220/)
- [GuJian 2](https://steamdb.info/app/570770/)
- [Demonicon](https://steamdb.info/app/215630/)
- [Young Justice: Legacy](https://steamdb.info/app/235760/)
- [Stronghold Crusader 2](https://steamdb.info/app/232890/)
- [Kick-Ass 2](https://steamdb.info/app/304170/)
- [Bot Colony](https://steamdb.info/app/263040/)
- [BloodBath](https://steamdb.info/app/304150/)
- [Raven's Cry](https://steamdb.info/app/281130/)
- [World of Subways 4 – New York Line 7](https://steamdb.info/app/343070/)
- [SoulWorker](https://steamdb.info/app/630100/)
- [Modern Combat Versus](https://steamdb.info/app/723780/)
- [Gujian 3](https://steamdb.info/app/994280/)
- [Swords of Legends Online (Legend of the Ancient Sword Online)](https://steamdb.info/app/1418100/)
- [Stronghold: Warlords](https://steamdb.info/app/907650/)
- [Line of Defense](https://steamdb.info/app/266620/)

### Possible way to detect it

every game has vision[ver number].dll, for example vision100.dll - vision 10.0, vision79.dll - vision 7.9

**Comment by diedyesterdaywashere** [comment]
@Lifeismana maybe you know how to make regex pick up any vision[ver].dll? because adding every single version would take a long time

**Comment by Lifeismana** [comment]
not worth it to try to match every number possible just take the versions that are used:

Most common base names:
* `vision71.dll` - 7 matches
* `libp3vision.dll` - 7 matches
* `vision90.dll` - 5 matches
* `vision.dll` - 2 matches
* `vision80.dll` - 2 matches
* `subdivision.dll` - 2 matches
* `vision100.dll` - 1 matches
* `revision.dll` - 1 matches

**Comment by diedyesterdaywashere** [comment]
> not worth it to try to match every number possible just take the versions that are used:
> 
> Most common base names:
> 
> * `vision71.dll` - 7 matches
> * `vision90.dll` - 5 matches
> * `vision.dll` - 2 matches
> * `vision80.dll` - 2 matches
> * `vision100.dll` - 1 matches

but how to make regex look into different names? with just one rule?

**Comment by Lifeismana** [comment]
(?:71|80|90|100|)

**Comment by diedyesterdaywashere** [comment]
so it just goes like `(?:^|/)vision(?:71|80|90|100|)\.dll$`?

**Comment by Lifeismana** [comment]
yes, if my regex knowledge isn't wrong
