### ISSUE TITLE
Add Miles detection

### ISSUE THREAD

**Issue by LinXP** [SteamDatabase/FileDetectionRuleSets#243]
### Some reference to the SDK, such as the developer site or a wikipedia article.

The Miles Sound System http://www.radgametools.com/miles.htm

### SteamDB links

https://steamdb.info/app/1135240/
https://steamdb.info/app/201230/
https://steamdb.info/app/253920/
https://steamdb.info/app/2210/

### Possible way to detect it

Contain any of the files: mss16.dll, mss32.dll, mss64.dll

**Comment by diedyesterdaywashere** [comment]
made a rule for it, now we need to wait for collaborators
