### ISSUE TITLE
Add OpenSSL detection

### ISSUE THREAD

**Issue by LinXP** [SteamDatabase/FileDetectionRuleSets#253]
### Some reference to the SDK, such as the developer site or a wikipedia article.

OpenSSL: https://www.openssl.org/

### SteamDB links

https://steamdb.info/app/529840/
https://steamdb.info/app/1238060/
https://steamdb.info/app/295950/

### Possible way to detect it

Contain any of the files: libeay32.dll, ssleay32.dll

**Comment by diedyesterdaywashere** [comment]
yo, thanks for a lot of sdks and stuff, i have something to do now xD
