### ISSUE TITLE
Add Smacker Video detection

### ISSUE THREAD

**Issue by LinXP** [SteamDatabase/FileDetectionRuleSets#255]
### Some reference to the SDK, such as the developer site or a wikipedia article.

Smacker Video: http://www.radgametools.com/smkmain.htm

### SteamDB links

https://steamdb.info/app/215930
https://steamdb.info/app/549170
https://steamdb.info/app/410980

### Possible way to detect it

Contain any of the file: smackw32.dll

**Comment by LinXP** [comment]
Proposal to merge into one group RAD, as Nvidia..
RAD.Bink_Video, RAD.Smacker_Video, RAD.Oodle, RAD.Miles, RAD.Granny

**Comment by diedyesterdaywashere** [comment]
i think nvidia's naming is like that because of the official name of the technology

**Comment by diedyesterdaywashere** [comment]
RAD's technology is just Granny or Miles Sound System, but not RAD Miles Sound System i think

**Comment by diedyesterdaywashere** [comment]
otherwise Oodle and Bink would get named like that already

**Comment by LinXP** [comment]
> RAD, or Epic Games Tools (formerly RAD Game Tools), is an Epic Games company based in Bellevue, Washington. 

http://www.radgametools.com/aboutrad.htm

**Comment by diedyesterdaywashere** [comment]
![image](https://user-images.githubusercontent.com/81169193/219974764-a5fc98ac-6eb1-4037-ae9a-7ce161127467.png)
but if you go on the bink page it just says bink

**Comment by diedyesterdaywashere** [comment]
and if you go on the [nvidia dlss](https://www.nvidia.com/en-us/geforce/technologies/dlss/) page it says nvidia dlss

**Comment by LinXP** [comment]
As you see fit. At your own discretion

I'm more interested in this [(?:^|/)bink2?w(?:64|32)?\.dll$](https://github.com/SteamDatabase/FileDetectionRuleSets/blob/7b0ba6345c69b39dcd770378eabc24aa1b394c2d/rules.ini#L162)
there is also binkw32.dll and binkw64.dll

**Comment by diedyesterdaywashere** [comment]
i can try making an update for it after i make a pr for this smacker video thing

**Comment by diedyesterdaywashere** [comment]
> As you see fit. At your own discretion
I am not the one deciding things though, im just a contributor who makes regexes in my free time, so if xPaw of Collaborators choose to name it "RAD *Technology*" it'll be their choice

**Comment by diedyesterdaywashere** [comment]
sorry, i'll probs go to bed now, but you can make more issues overnight and me/other people will make regexes for them

**Comment by diedyesterdaywashere** [comment]
![image](https://user-images.githubusercontent.com/81169193/219975439-cb24e4d6-8df2-480a-a259-8f6fce160bcd.png)
actually, according to tests file binkw files are already getting checked, and if bink tech is on website regex probably works

**Comment by diedyesterdaywashere** [comment]
also, you are Ukrainian according to your github page, so if you want to discuss something in Ukrainian you can dm me on discord (diedyesterday#5745), since im pretty sure english is the only language available here, and using Ukrainian will be easier for both of us
