### ISSUE TITLE
LibGDX, also add [Framework] section

### ISSUE THREAD

**Issue by Suvitruf** [SteamDatabase/FileDetectionRuleSets#26]
### Some reference to the engine, such as the developer site or a wikipedia article.

https://github.com/libgdx/libgdx

### SteamDB links

https://steamdb.info/app/646570/

Also, please add [Framework] section for frameworks like LibGDX.

**Comment by xPaw** [comment]
Sections are not special, so they can be added trivially.

**Comment by Suvitruf** [comment]
> Sections are not special, so they can be added trivially.
> 
> I don't see libGDX files in Slay the spire, does it have a different name?

You can check it by opening final .jar, there wil be com.badlogic package. But probable there is no files which 100% specific exactly for LibGDX. So you can't detect this framework onlt by filenames )=

**Comment by xPaw** [comment]
Welp.
