### ISSUE TITLE
Lumberyard not being detected (or being detected as CryEngine)

### ISSUE THREAD

**Issue by TotallyGatsby** [SteamDatabase/FileDetectionRuleSets#27]
### Some reference to the engine, such as the developer site or a wikipedia article.

Amazon developed a variant of CryEngine called Lumberyard:
* https://aws.amazon.com/lumberyard/
* https://en.wikipedia.org/wiki/Amazon_Lumberyard

### SteamDB links

https://steamdb.info/app/1057240/
https://steamdb.info/app/1426320/
https://steamdb.info/app/583240/

### Possible way to detect it

engine.json file contains which might be useful:

```
{
    "FileVersion": 1,
    "LumberyardVersion": "1.17.0.0",
    "LumberyardCopyrightYear": 2018
}
```

**Comment by Lifeismana** [comment]
from #190 
looking for bootstrap.cfg could be an idea but it seems like there's too many false positive

* [583241 - Coffence Content](https://steamdb.info/depot/583241/)
* [613581 - The DRG Initiative Content](https://steamdb.info/depot/613581/)
* [949521 - Lost On The Island Content](https://steamdb.info/depot/949521/)
* [1057241 - Crucible Content](https://steamdb.info/depot/1057241/)
* [1063731 - Main Game Content](https://steamdb.info/depot/1063731/)
* [1129071 - Dedicated Server Content](https://steamdb.info/depot/1129071/)
* [1205551 - New World Public Test Realm](https://steamdb.info/depot/1205551/)
* [1368991 - Shatterline Content](https://steamdb.info/depot/1368991/)
* [1426321 - New World Alpha Content](https://steamdb.info/depot/1426321/)
* [1705021 - AimGoGoGo Content](https://steamdb.info/depot/1705021/)
* [1724661 - New World Open Beta Content](https://steamdb.info/depot/1724661/)
* [1937051 - ](https://steamdb.info/depot/1937051/)
* [2087031 - ](https://steamdb.info/depot/2087031/)
* [2089761 - ](https://steamdb.info/depot/2089761/)

**Comment by diedyesterdaywashere** [comment]
> from #190 looking for bootstrap.cfg could be an idea but it seems like there's too many false positive
> 
> * [583241 - Coffence Content](https://steamdb.info/depot/583241/)
> * [613581 - The DRG Initiative Content](https://steamdb.info/depot/613581/)
> * [949521 - Lost On The Island Content](https://steamdb.info/depot/949521/)
> * [1057241 - Crucible Content](https://steamdb.info/depot/1057241/)
> * [1063731 - Main Game Content](https://steamdb.info/depot/1063731/)
> * [1129071 - Dedicated Server Content](https://steamdb.info/depot/1129071/)
> * [1205551 - New World Public Test Realm](https://steamdb.info/depot/1205551/)
> * [1368991 - Shatterline Content](https://steamdb.info/depot/1368991/)
> * [1426321 - New World Alpha Content](https://steamdb.info/depot/1426321/)
> * [1705021 - AimGoGoGo Content](https://steamdb.info/depot/1705021/)
> * [1724661 - New World Open Beta Content](https://steamdb.info/depot/1724661/)
> * [1937051 - ](https://steamdb.info/depot/1937051/)
> * [2087031 - ](https://steamdb.info/depot/2087031/)
> * [2089761 - ](https://steamdb.info/depot/2089761/)

Had to google a lot but i am only not sure about 949521, all other games are Lumberyard since they are Amazon's or google says they're Lumberyard lmao
