### ISSUE TITLE
Multiple BattlEye Negatives

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#277]
### SteamDB link to the game

https://steamdb.info/app/113400
https://steamdb.info/app/489940
https://steamdb.info/app/728540/
https://steamdb.info/app/593600
https://steamdb.info/app/376210

### What should it be detected as?

AntiCheat.BattlEye

**Comment by Lifeismana** [comment]
Seems like these games are using a launcher to install it (and don't have any file about it in their depot), so there's nothing we can do about it
