### ISSUE TITLE
Add Denuvo Anti-Cheat

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#278]
### Some reference to the Anti-Cheat, such as the developer site or a wikipedia article.

https://irdeto.com/denuvo/anti-cheat/

### SteamDB links

https://steamdb.info/app/1359090/

**Comment by Lifeismana** [comment]
afaik, denuvo is entirely in the game's exe, so we won't be able to find it

**Comment by diedyesterdaywashere** [comment]
ah, rip
