### ISSUE TITLE
Add HackShield detection

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#283]
### Some reference to the Anti-Cheat, such as the developer site or a wikipedia article.

https://www.gamedeveloper.com/pc/ahnlab-announces-u-s-launch-of-hackshield-mmo-tech

### SteamDB links

https://steamdb.info/app/905640/ - might not use it anymore
https://steamdb.info/app/550900/

**Comment by MichaelHinrichs** [comment]
I didn't find anything about HackSheild in either of those games, but I did find it in these.
https://steamdb.info/app/231060/
https://steamdb.info/app/384030/
https://steamdb.info/app/2241570/
