### ISSUE TITLE
Luck be a Landlord

### ISSUE THREAD

**Issue by akien-mga** [SteamDatabase/FileDetectionRuleSets#29]
### SteamDB link to the game

https://steamdb.info/app/1404850

### What should it be detected as?

Godot

### Additional information

(Note: There's no box in the issue form to provide additional details when relevant, might be worth adding.)

Luck be a Landlord is made with Godot, but it's a tricky one to detect as it uses the "Embed PCK" option that embeds the `.pck` file with the game data inside the Godot executable (so it ships as a single `.exe`).

There's one way this can still be detected if we have access to the Mac files, as the `.pck` is included in the `.app`:

```
Luck be a Landlord.app/Contents/Resources/Luck be a Landlord.pck
```

There's no "Embed PCK" option for macOS exports, so for games which do provide a macOS build this should be a fairly good rule.

**Comment by xPaw** [comment]
There's literally only an exe file, not much we can do about it. https://steamdb.info/depot/1404851/

At least the mac build has a pck https://steamdb.info/depot/1404852/ (so if we apply same logic of checking the name as we do for exe, that would work).

**Comment by akien-mga** [comment]
Thanks for the fix! While browsing other entries detected as Godot, I noticed something that might warrant a slight adjustment to your fix:
https://steamdb.info/depot/1507975/

This is very likely a Godot game, but note how the `.app` name and the `.pck` name differ. The `.pck` actually has to match the name of the game binary:
```
文字遊戲：第零章.app/Contents/MacOS/Word Game
文字遊戲：第零章.app/Contents/Resources/Word Game.pck
```

They should respectively always be in `Contents/MacOS/` and `Contents/Resources/`, but the `.app` itself can have an arbitrary name.
