### ISSUE TITLE
Add PyGame

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#290]
### Some reference to the engine, such as the developer site or a wikipedia article.

https://www.pygame.org/

### SteamDB links

https://steamdb.info/app/951360/
https://steamdb.info/app/550900/
https://steamdb.info/app/442210/

### Possible way to detect it

not sure

**Comment by MichaelHinrichs** [comment]
here are a couple that are more accessible.
https://steamdb.info/app/918170/
https://steamdb.info/app/2363270/
