### ISSUE TITLE
Split UnityEngine into Il2cpp and Mono separately

### ISSUE THREAD

**Issue by Glatrix** [SteamDatabase/FileDetectionRuleSets#311]
### Some reference to the engine, such as the developer site or a wikipedia article.

// Mono
https://docs.unity3d.com/Manual/Mono.html
https://www.mono-project.com/

// IL2CPP
https://docs.unity3d.com/Manual/IL2CPP.html

### SteamDB links

--Both IL2CPP and Mono are UnityEngine. But they are compiled differently

IL2CPP:
https://steamdb.info/app/739630/
https://steamdb.info/app/945360/

Mono:
https://steamdb.info/app/1625450/
https://steamdb.info/app/477160/

### Possible way to detect it

Can use UnityPlayer.dll to tell if the game is UnityEngine. From there check
if GameAssembly.dll exists in the root game folder and if so its Il2cpp, otherwise
its Mono. Another difference is the presence of the Managed folder in Game_Data folder.
Mono has this folder but Il2cpp does not as it packs all these dlls into 1 single dll, which
is GameAssembly.dll

**Comment by diedyesterdaywashere** [comment]
as you said **they are both the same engine**, why  split them then, even if they are compiled differently, its the same engine after all
