### ISSUE TITLE
Penny Arcade's On the Rain-Slick Precipice of Darkness 3

### ISSUE THREAD

**Issue by MichaelHinrichs** [SteamDatabase/FileDetectionRuleSets#317]
### SteamDB link to the game

https://steamdb.info/app/213030/info/

### What is it being detected as and what should it be detected as? Any other information?

This game is detected as unity. It's actually XNA.

**Comment by Lifeismana** [comment]
The Mac OS version uses unity
`Penny Arcade's On The Rain-Slick Precipice of Darkness 3.app/Contents/Data/Managed/UnityEngine.dll`

**Comment by MichaelHinrichs** [comment]
I see. Still, XNA is undetected in the windows version. I guess this should be relabeled as a false negative.

**Comment by MichaelHinrichs** [comment]
So is anyone going to re-tag it, or what?
