### ISSUE TITLE
Village of Adventurers 2

### ISSUE THREAD

**Issue by akien-mga** [SteamDatabase/FileDetectionRuleSets#33]
### SteamDB link to the game

https://steamdb.info/app/727090/info/

### What is it being detected as and what should it be detected as? Any other information?

Detected as Godot, but it *very likely* isn't. I don't have the game to confirm but the file structure doesn't look too common for Godot, and the executable is too small.
https://steamdb.info/depot/727091/

Similar to #22 - based on the file names only, this *could* be Godot, albeit with a fairly rare use of it, especially for the `data.pck` (pre 3.0) era.

I'd suggest changing the heuristic so that `data.pck` + multiple other `.pck`s no longer match as Godot. There's only a handful of Godot games released on Steam with versions earlier than 3.0 (2018), and I doubt many of them use multiple PCKs.

*Edit:* If we can get a list of all entries with `data.pck` + multiple other `.pck`s, I'm happy to go through it and check if anything sounds like it might really be Godot. Otherwise we can use this exclude rule.

Other possibility: Check .exe file size. Current Windows 64-bit exe files for Godot are bigger than 30 MiB. Might have been closer to 20 MiB in the Godot 2.x era, but 4 MiB like here is definitely not possible.

**Comment by larsiusprime** [comment]
In my Godot PR this would not match Godot.
