### ISSUE TITLE
HaemimontSol

### ISSUE THREAD

**Issue by ivanassen** [SteamDatabase/FileDetectionRuleSets#34]
### Some reference to the engine, such as the developer site or a wikipedia article.

The Sol engine is the in-house engine of Haemimont Games (https://en.wikipedia.org/wiki/Haemimont_Games). It has been in constant development since 2005, and has about 10 titles on Steam, with more on the way. 

https://steamdb.info/search/?a=app_keynames&type=1&keyname=23&operator=3&keyvalue=Haemimont+Games

(Note: some of the older titles like Tzar and Rising Kingdoms are based on an earlier engine, not Sol)

### SteamDB links

Surviving Mars: https://steamdb.info/app/464920/
Victor Vran: https://steamdb.info/app/345180/

### Possible way to detect it

A folder called Packs/ contains multiple *.hpk files in it.
A folder called Local/ contains more *.hpk files, and all games so far have English.hpk (the default localization, English)

**Comment by xPaw** [comment]
Is `Local/English.hpk` guaranteed to exist (from root folder)? If so, that's an easy detection.

**Comment by ivanassen** [comment]
It is guaranteed to exist in one of the depots, but not on every users' disk - e.g. if the user has chosen German language, they will only have German.hpk there.
