### ISSUE TITLE
Multiple Prism3D Undetected Games

### ISSUE THREAD

**Issue by diedyesterdaywashere** [SteamDatabase/FileDetectionRuleSets#368]
### SteamDB link to the game

[18 Wheels of Steel: Hard Truck](https://steamdb.info/app/1318750/)
[Hunting Unlimited](https://steamdb.info/app/1267940/)

*[PCGamingWiki also says that Duke Nukem: Manhattan Project uses "Prism3D" but for some reason, i don't think it's the same engine](https://www.pcgamingwiki.com/wiki/Duke_Nukem:_Manhattan_Project#:~:text=Engines,Prism3D) [(steamdb link for that game)](https://steamdb.info/app/240200/)*

### What should it be detected as?

Engine.Prism3D

**Comment by MichaelHinrichs** [comment]
Well Duke Nukem: Manhattan Project does have some files named "prism3d". That seems like solid evidence to me. What makes you think it's something else?

**Comment by diedyesterdaywashere** [comment]
i'm saying that it might be "prism3d" but not the same one, compare the games, it just doesn't look anything like the other ones
