### ISSUE TITLE
End Reach

### ISSUE THREAD

**Issue by akien-mga** [SteamDatabase/FileDetectionRuleSets#37]
### SteamDB link to the game

https://steamdb.info/app/1454550/info/

### What should it be detected as?

Godot

### Additional information

The Windows depot looks like it should match the rule sets for Godot: https://steamdb.info/depot/1389032/

Maybe it's fooled by the fake `.exe` in the `__MACOSX` folder?

**Comment by larsiusprime** [comment]
Passes in my Godot PR
