### ISSUE TITLE
my brother lives in a canyon

### ISSUE THREAD

**Issue by akien-mga** [SteamDatabase/FileDetectionRuleSets#38]
### SteamDB link to the game

https://steamdb.info/app/1641020/

### What should it be detected as?

Godot

### Additional information

Both Windows and Linux depots look like they should match Godot fine. It's a recent release so maybe it's just a matter of not having had a token for it at the time of the last analysis?

**Comment by larsiusprime** [comment]
Checked and this passes in my new Godot PR
