### ISSUE TITLE
Project Kat - Paper Lily Prologue

### ISSUE THREAD

**Issue by overwatcheddude** [SteamDatabase/FileDetectionRuleSets#389]
### SteamDB link to the game

https://steamdb.info/app/1698960/

### What should it be detected as?

Engine.Godot

**Comment by akien-mga** [comment]
Sadly this game can't reasonably be detected with file based heuristics. It doesn't include clear Godot markers that would not lead to false positives.

https://steamdb.info/depot/1698961/

- It bundles the main game data pack in the .exe file, so there's only `ProjectKat.exe`, not `ProjectKat.exe` + `ProjectKat.pck`. The latter combination would confirm it's a Godot game, but without it we can't be sure.
- It does include additional `.pck` files which are loaded on demand (translations, etc.), but this extension isn't specific to Godot.
- It uses Mono, so it has a `data_<Project Name>` folder, but the actual project name differs from the game / .exe name they chose, so even that couldn't be reliably matched here (I don't think we try to match these though). I don't think any of the files in the `data_<Project Name>` folder can reasonably infer that it's Godot, Unity C# games typically have a similar structure.
- Doesn't use popular GDNative/GDExtension addons like GodotSteam, which would add a `godotsteam.dll` which can be a good marker.
- No macOS build, which is usually a good fallback when the Windows build embeds the PCK file, as this can't be done for macOS so the `GameName.pck` file would be detected.
