### ISSUE TITLE
Captain Diarrhea and The Shartening

### ISSUE THREAD

**Issue by overwatcheddude** [SteamDatabase/FileDetectionRuleSets#390]
### SteamDB link to the game

https://steamdb.info/app/1727400/

### What should it be detected as?

Engine.Godot

**Comment by akien-mga** [comment]
Impossible to detect based on the files:
https://steamdb.info/depot/1727401/
https://steamdb.info/depot/1727402/

It uses the "Embed PCK" option, so there's just a single binary, from the files only it could be any engine that can compile to a self-contained binary.
