### ISSUE TITLE
Maces and Dices - Detectable Godot game but from "SteamDB Unknown Depot"

### ISSUE THREAD

**Issue by akien-mga** [SteamDatabase/FileDetectionRuleSets#397]
### SteamDB link to the game

https://steamdb.info/app/2434720

This game's only depot has files which match the Godot heuristics: https://steamdb.info/depot/2434721/

But the depot must be wrongly configured in Steamworks, and shows up as "SteamDB Unknown Depot" instead of a "Windows" depot. I'm assuming it still works somewhat otherwise the dev would have fixed it since releasing the game 3 weeks ago.

So maybe such depots should still be parsed for engine detection?

### What should it be detected as?

Engine.Godot

**Comment by xPaw** [comment]
It didn't get updated because it only got the depot key recently (https://steamdb.info/donate/)

Steam doesn't expose depot names anymore that's why they're unknown.
