### ISSUE TITLE
Infinity Engine games are being detected as Aurora

### ISSUE THREAD

**Issue by Duffadash** [SteamDatabase/FileDetectionRuleSets#49]
### SteamDB link to the game

https://steamdb.info/app/228280/
https://steamdb.info/app/257350/
https://steamdb.info/app/466300/
https://steamdb.info/app/321800/

### What is it being detected as and what should it be detected as? Any other information?

Infinity Engine games are currently tagged as Aurora.

Complete list of Infinity Engine games on Steam:
https://steamdb.info/app/228280/
https://steamdb.info/app/257350/
https://steamdb.info/app/385970/
https://steamdb.info/app/321800/
https://steamdb.info/app/466300/

Complete list of Aurora Engine games on Steam:
https://steamdb.info/app/704450/
https://steamdb.info/app/2760/
https://steamdb.info/app/32370/
https://steamdb.info/app/208580/
https://steamdb.info/app/7110/
https://steamdb.info/app/20900/
https://steamdb.info/app/17450/
https://steamdb.info/app/1238040/

**Comment by larsiusprime** [comment]
Question about the Infinity Engine as I am ignorant --- I know the infinity engine is what the *original* Baldur's gate was made in, but what's the situation with Baldur's gate enhanced edition, which was made over a decade later? Is it an updated version of the same engine? What's the relationship between Aurora and Infinity engine?

**Comment by Duffadash** [comment]
I'm going by Wikipedia here:

> BioWare created the Infinity Engine to use it as a core component for development of 2D role-playing video games based on Dungeons & Dragons, the Baldur's Gate series (1998–2001). The engine was also used by Black Isle Studios to create the critically acclaimed Planescape: Torment (1999) and the Icewind Dale series (2000–2002). When Beamdog sought out a license from BioWare and started engineering enhanced versions of these games in 2012, they created an updated version Infinity Engine, referred to as the "**Infinity Enhanced Engine**" (alternatively **Infinity Plus Engine** or **Infinity Bless Engine**).

So there are two version of the Infinity Engine, the original and the enhanced one.

Aurora Engine is somewhat more complicated, since it was updated and had a name change with seemingly each subsequent game made in it. It's a completely separate engine from the Infinity Engine, capable of handling 3D environments.
Neverwinter Nights, The Witcher - Aurora Engine
Neverwinter Nights 2 - Electron Engine
KOTOR, KOTOR 2 and Jade Empire - Odyssey Engine
Dragon Age: Origins - Eclipse Engine
Dragon Age II - Lycium Engine
Also Sonic Chronicles: The Dark Brotherhood runs some kind of Aurora Engine, but that is unlikely to come up, what with it being exclusively a Nintendo DS game.

These are essentially still just updates of the Aurora engine. The Neverwinter Nights Enhanced Edition seems to merely be a bundle of Neverwinter Nights with community fixes and a replacement of the dead multiplayer functionality.

Sources:
https://en.wikipedia.org/wiki/BioWare#Technology
https://github.com/xoreos/xoreos
https://en.wikipedia.org/wiki/Neverwinter_Nights_(2002_video_game)#Editions_and_re-releases
https://witcher.fandom.com/wiki/Aurora_Engine

**Comment by larsiusprime** [comment]
Okey doke, that is sufficient for me. 

Seems like a similar situation with e.g. the early idTech engines that went open source, particularly doom -- ChocolateDoom and all that still count as the Doom Engine to me, because that's the only reasonably coherent way to deal with this, and it works well with our philosophy of detection by file names signatures because many "improved" engines have very similar or identical file structures to what they are dropped in to replace.

So we'll go with "Infinity engine" for these titles, regardless of how "enhanced" said infinity engine is, and "Aurora engine" for the other stuff, even if they like to give each release its own code engine. Kinda like how Android is still Android, regardless of what candy flavored codename this particular version is stamped with.

**Comment by larsiusprime** [comment]
Just pushed a change that should distinguish these correctly. Close this issue if they seem correct after the next update.

**Comment by Duffadash** [comment]
It's still not quite right.
For both Infinity Engine games and Aurora Engine games you can expect to find the following files:
chitin.key
dialog.tlk
data/

For Aurora Engine games specifically you can also expect one or more of the following folders:
modules/
miles/
localvault/
texturepacks/
shaderpc/

Also the Infinity Engine data folder always contains a bunch of .bif files, that does not seem to be the case with Aurora engine data/ folders. Neverwinter Nights, KOTOR 1 and 2 has a data/ folder containing .bif files, but Jade Empire has .rim files, Neverwinter Nights 2, The Witcher and Dragon Age Origins have all sorts of files in their data/ folders.
