### ISSUE TITLE
One Way To Die

### ISSUE THREAD

**Issue by akien-mga** [SteamDatabase/FileDetectionRuleSets#51]
### SteamDB link to the game

https://steamdb.info/app/388490/info/

### What should it be detected as?

Godot

**Comment by akien-mga** [comment]
It *should* match in theory with the current rules, but I suspect that maybe the rules don't handle pre-Godot 3.0 macOS builds properly (i.e. there's a `data.pck` in `*.app/Contents/Resources/`):

https://steamdb.info/depot/388499/

```
One Way To Die.app/Contents/MacOS/One Way To Die
One Way To Die.app/Contents/Resources/data.pck
```

**Comment by larsiusprime** [comment]
This passes in my current tests.
