### ISSUE TITLE
Steam cloud (and maybe other steam apis?)

### ISSUE THREAD

**Issue by squeak9** [SteamDatabase/FileDetectionRuleSets#547]
### Some reference to the SDK, such as the developer site or a wikipedia article.

https://partner.steamgames.com/doc/features/cloud

You can also see it on game pages but not search for it: https://steamdb.info/app/400/ufs/

### SteamDB links

One that lists Steam cloud as a feature: https://steamdb.info/app/1145360/ufs/

One that doesn't https://steamdb.info/app/400/ufs/

### Possible way to detect it

I know this tool can search for games that show they use the Steam Cloud feature; here is a search for games that supposedly doesn't use it. https://steamdb.info/instantsearch/?refinementList%5Bcategories%5D%5B0%5D=-Steam%20Cloud
The problem is that lots of games on this list use Steam Cloud even though they don't advertise it, example with Portal: https://steamdb.info/app/400/ufs/

I'm curious about what games that actually uses Steam Cloud and what games don't etc so that's why i want this advanced search feature, maybe this is the wrong place to ask for it?

**Comment by diedyesterdaywashere** [comment]
best we can do is detect the steam sdk itself, since it's all contained inside one file called steam_api.dll

**Comment by squeak9** [comment]
But the website can detect it somehow right? Every game page either has that cloud tab doesn't have it, I just want it searchable.
Maybe this out of the scope for this repo...

**Comment by diedyesterdaywashere** [comment]
> But the website can detect it somehow right? Every game page either has that cloud tab doesn't have it, I just want it searchable. Maybe this out of the scope for this repo...

yeah it is, in this repo we're detecting technologies (Unity, Unreal Engine, etc.) using files inside game depots

**Comment by diedyesterdaywashere** [comment]
https://steamdb.info/instantsearch/?refinementList%5Bcategories%5D%5B0%5D=Steam%20Cloud you can see all the games that offer this feature (and notify about it on their store page) here

**Comment by squeak9** [comment]
That search is missing all the games that doesn't list it on the store page though: https://steamdb.info/instantsearch/?refinementList%5Bcategories%5D%5B0%5D=Steam%20Cloud 
Makes it tricky to find a list that shows games that actually doesn't support steam cloud.

**Comment by diedyesterdaywashere** [comment]
> That search is missing all the games that doesn't list it on the store page though: https://steamdb.info/instantsearch/?refinementList%5Bcategories%5D%5B0%5D=-Steam%20Cloud Makes it tricky to find a list that shows games that actually doesn't support steam cloud.

https://github.com/SteamDatabase/steamdb.info-issues

you should probably open an issue here, as we can't help you with it here

**Comment by squeak9** [comment]
Gotcha, thanks for the info. 👍 

I thought it kinda would fit on this page but i guess not https://steamdb.info/tech/

**Comment by Lifeismana** [comment]
> https://github.com/SteamDatabase/steamdb.info-issues
>
> you should probably open an issue there, as we can't help you with it here
No, steamdb is not steam, it's the devs fault for not marking it correctly, there's nothing steamdb can do about that

**Comment by diedyesterdaywashere** [comment]
> > https://github.com/SteamDatabase/steamdb.info-issues
> > you should probably open an issue there, as we can't help you with it here
> 
> No, steamdb is not steam, it's the devs fault for not marking it correctly, there's nothing steamdb can do about that

i know, but all the games that have the feature have /ufs/ page on steamdb, so i guess it would be possible to sort the games using it?
