### ISSUE TITLE
Add ShiVa3D detection

### ISSUE THREAD

**Issue by LinXP** [SteamDatabase/FileDetectionRuleSets#586]
### Some reference to the engine, such as the developer site or a wikipedia article.

https://web.archive.org/web/20180718043215/http://www.shiva-engine.com/
https://es.wikipedia.org/wiki/ShiVa

### SteamDB links

https://steamdb.info/app/346440/
https://steamdb.info/app/279520/

### Possible way to detect it

Contains files: S3DClient.cfg
*.stk

**Comment by Lifeismana** [comment]
looking for `.stk` files will match every app that have `S3DClient.cfg`, so we only need to keep this one (`.stk`), do you want to do the PR for it ?

**Comment by LinXP** [comment]
High probability of false positives, it is better to search only for the file `S3DClient.cfg`

**Comment by Lifeismana** [comment]
Nah, i checked, the ones non detected by checking only the cfg are using that "engine"

**Comment by LinXP** [comment]
Ok, then at your discretion, create a PR
