### ISSUE TITLE
Apex Legends

### ISSUE THREAD

**Issue by Barmem** [SteamDatabase/FileDetectionRuleSets#59]
### SteamDB link to the game

https://steamdb.info/app/1172470/

### What should it be detected as?

Engine.Source

**Comment by xPaw** [comment]
Apex is heavily modified, it won't be detected as Source.

**Comment by Barmem** [comment]
.vpk files are a huge flag that its source, isn't it?
![изображение](https://user-images.githubusercontent.com/70278808/129158942-a14d0a46-3a84-49ff-add1-6e22581f3e88.png)

**Comment by xPaw** [comment]
vpks also exist in source 2

**Comment by Barmem** [comment]
Could be a detection for groups of engines? Titanfall 1 and 2 supposedly are also heavily modified source but detected as source

**Comment by xPaw** [comment]
Actually yeah, it's not hard to check that it has a vpk and it's not detected as source2, I'll add that.
