### ISSUE TITLE
Detect nw.js

### ISSUE THREAD

**Issue by Maelfyn** [SteamDatabase/FileDetectionRuleSets#67]
### Some reference to the SDK, such as the developer site or a wikipedia article.

https://nwjs.io/

### SteamDB links

This is the only one I'm aware of (my own project). It's very similar to Electron, but less popular.

https://steamdb.info/app/853450/

### Possible way to detect it

I believe these would be some good candidates to detect nw.js:

In the top-level directory:
icudtl.dat
node.dll
nw.dll
nw_100_percent.pak
nw_200_percent.pak
nw_elf.dll
nwjc.exe
payload.exe
pnacl (folder)
resources.pak

**Comment by ToughGuyKunio** [comment]
This game is also NW.js: https://steamdb.info/app/293440/
