### ISSUE TITLE
[Build Engine] Tomb Raider I

### ISSUE THREAD

**Issue by Pois0nous** [SteamDatabase/FileDetectionRuleSets#7]
### SteamDB link to the game

https://steamdb.info/app/224960/

### What should it be detected as?
Core Design had an in-house engine without any name, probably "Tomb Raider Engine"

**Comment by SinZ163** [comment]
If it isn't meant to be Emulator.DOSBOX / SDK.SDL what is it meant to be?

**Comment by Pois0nous** [comment]
The problem is with the Engine. It's not a Build Engine game. There are a bunch of false positives in Build category. I think this rule caused them:

`Build[] = (?:^|/)HMIDET\.386$`

This file is not Build Engine exclusive. I'm not sure btw

**Comment by larsiusprime** [comment]
We've removed that rule as it was causing way too many false positives. Should be good now? I guess we'll leave Tomb Raider uncategorized for now.
