### ISSUE TITLE
Engine: 3D Gamestudio aka Gamestudio A8

### ISSUE THREAD

**Issue by Superku** [SteamDatabase/FileDetectionRuleSets#70]
### Some reference to the engine, such as the developer site or a wikipedia article.

3D Gamestudio, oftentimes only referred to as Gamestudio, is a very old school toolset (engine + editors) which some people used before Unity was a thing. It might be referred to as A8 as well, short for Acknex 8 (rolls right of the tongue, right?).

Super old school homepage: http://www.conitec.net/english/gstudio/index.PHP
Manual and API reference: http://manual.3dgamestudio.net/

It's a Windows only 32bit DirectX 9.0c engine. It's hell to work with.

### SteamDB links

(My game: ) https://steamdb.info/app/688130/

https://steamdb.info/app/724390/

https://steamdb.info/app/34900/

https://steamdb.info/app/259640/

https://steamdb.info/app/280640/

Some of those are made with previous iterations of Gamestudio (A4 through A8) but they all contain the same base data.

### Possible way to detect it

The engine DLL **acknex.dll** should be included in pretty much every game made with this toolset.
*.wrs container files are present if the game creator owns the Pro version of the engine.
A file called acknex.wdf, a starter window definition, might be present, as well as d3dx9_42.dll and/ or d3dx9_32.dll and d3dx9_30.dll files. Furthermore, d3dcompiler_42.dll might be included in most games.

**Comment by xPaw** [comment]
I'm seeing a few games where the dll is not present but the wdf file is. Can you verify the list please?

It could be great if you could make a PR for it. `(?:^|/)acknex\.(?:dll|wdf)$`

Most common base names:
* `acknex.dll` - 57 matches
* `acknex.wdf` - 50 matches

Depots that matched:
* [15501 - The Wonderful End of the World content](https://steamdb.info/depot/15501/)
* [15511 - The Wonderful End of the World demo content](https://steamdb.info/depot/15511/)
* [15521 - aaaaa content](https://steamdb.info/depot/15521/)
* [15531 - aaaaa-demo-depot](https://steamdb.info/depot/15531/)
* [34903 - Bad Rats - Master 1](https://steamdb.info/depot/34903/)
* [34911 - Bad Rats - Demo](https://steamdb.info/depot/34911/)
* [34921 - Razor2](https://steamdb.info/depot/34921/)
* [34931 - Razor2 Demo](https://steamdb.info/depot/34931/)
* [209061 - Drunken Robot Pornography Content](https://steamdb.info/depot/209061/)
* [259642 - Core Files](https://steamdb.info/depot/259642/)
* [273772 - Game Tycoon 1.5 English](https://steamdb.info/depot/273772/)
* [273773 - Game Tycoon 1.5 German](https://steamdb.info/depot/273773/)
* [280641 - Base Content](https://steamdb.info/depot/280641/)
* [336201 - Starlaxis English](https://steamdb.info/depot/336201/)
* [336202 - Starlaxis German](https://steamdb.info/depot/336202/)
* [339722 - Debugger V1.0 English](https://steamdb.info/depot/339722/)
* [339723 - Debugger German](https://steamdb.info/depot/339723/)
* [353021 - Starlaxis Supernova Edition Demo English](https://steamdb.info/depot/353021/)
* [380951 - Bocce Revolution Default (english)](https://steamdb.info/depot/380951/)
* [412291 - The Dreamlord Content](https://steamdb.info/depot/412291/)
* [450031 - Worst Case Z Content](https://steamdb.info/depot/450031/)
* [459511 - ZULA Content](https://steamdb.info/depot/459511/)
* [502721 - Star Explorers Content](https://steamdb.info/depot/502721/)
* [507391 - Gone In November Content](https://steamdb.info/depot/507391/)
* [512151 - Swordlord Content](https://steamdb.info/depot/512151/)
* [513651 - Zula - Europe Content](https://steamdb.info/depot/513651/)
* [546781 - Anomalies Content](https://steamdb.info/depot/546781/)
* [546782 - Anomalies German](https://steamdb.info/depot/546782/)
* [553101 - Timber! The Logging Experts EN](https://steamdb.info/depot/553101/)
* [553102 - Timber! The Logging Experts DE](https://steamdb.info/depot/553102/)
* [587331 - MARS SIMULATOR - RED PLANET Content](https://steamdb.info/depot/587331/)
* [587332 - "MARS SIMULATOR - RED PLANET"-German](https://steamdb.info/depot/587332/)
* [587333 - "MARS SIMULATOR - RED PLANET"-French](https://steamdb.info/depot/587333/)
* [618081 - Martial Arts Brutality Content](https://steamdb.info/depot/618081/)
* [670761 - Sage 3D Content](https://steamdb.info/depot/670761/)
* [688131 - Pogostuck Content](https://steamdb.info/depot/688131/)
* [691701 - Triton Wing Content](https://steamdb.info/depot/691701/)
* [714211 - Zula Online Content](https://steamdb.info/depot/714211/)
* [724391 - Rigid Force Alpha Content](https://steamdb.info/depot/724391/)
* [724393 - Rigid Force Alpha Press Version Depot](https://steamdb.info/depot/724393/)
* [747611 - ZULA Latinoamérica Content](https://steamdb.info/depot/747611/)
* [761512 - Railroad Construction Simulator](https://steamdb.info/depot/761512/)
* [782163 - "Raptainment"-V1.1](https://steamdb.info/depot/782163/)
* [782164 - "Raptainment"-V1.1g](https://steamdb.info/depot/782164/)
* [793581 - Anomalies Demo Content](https://steamdb.info/depot/793581/)
* [807001 - My Grandfather's Farm Content](https://steamdb.info/depot/807001/)
* [844711 - Sage 3D Demo Content](https://steamdb.info/depot/844711/)
* [846141 - Debugger 3.16: Hack'n'Run Demo English](https://steamdb.info/depot/846141/)
* [846142 - Debugger 3.16: Hack'n'Run Demo Deutsch](https://steamdb.info/depot/846142/)
* [846851 - DearCraft CHS](https://steamdb.info/depot/846851/)
* [977091 - Kumpels Content](https://steamdb.info/depot/977091/)
* [1040451 - The King's New Castle Content](https://steamdb.info/depot/1040451/)
* [1051841 - Paradox Vector Content](https://steamdb.info/depot/1051841/)
* [1104591 - Bacillus Content](https://steamdb.info/depot/1104591/)
* [1189241 - Oil Mogul Content](https://steamdb.info/depot/1189241/)
* [1275491 - Martial Arts Brutality Premium Content](https://steamdb.info/depot/1275491/)
* [1315891 - Big City Rigs: Garbage Truck Driver Content](https://steamdb.info/depot/1315891/)
* [1317801 - Big City Rigs: Bus Driver Content](https://steamdb.info/depot/1317801/)
* [1584331 - Beth the Exhibitionist Content](https://steamdb.info/depot/1584331/)
* [1585251 - The Space Between Content](https://steamdb.info/depot/1585251/)

**Comment by Superku** [comment]
I'm on vacation now so sadly I only have very limited time until August 28th (got a GitHub email).

"I'm seeing a few games where the dll is not present but the wdf file is. Can you verify the list please?"

The DLL has 57 to 50 matches for the wdf starter file, no?

"It could be great if you could make a PR for it. (?:^|/)acknex\.(?:dll|wdf)$"

Sadly I do not know what that means just yet.

Do you have a link or an appID for a possible Gamestudio game with wdf starter but without acknex.dll?

**Comment by xPaw** [comment]
> The DLL has 57 to 50 matches for the wdf starter file, no?

That's why the regex I suggested includes both extensions.

> Do you have a link or an appID for a possible Gamestudio game with wdf starter but without acknex.dll?
https://steamdb.info/depot/507391/

**Comment by Superku** [comment]
> https://steamdb.info/depot/507391/

Ok. I've just tried to change the name of the DLL (to Kernel.dll as with the app in question). The exe cannot be launched then (could have worked as per default the engine tries to open all DLLs in the folder).
(The Kernel.dll file of 507391 has a size of about old acknex.dll files.)
In previous Gamestudio versions there was the option to use C-Script instead of lite-C, and C-Script games would be compiled at game launch on the fly if I'm not mistaken. So maybe that's why that game runs without a/ the acknex.dll.

> That's why the regex I suggested includes both extensions.

Sounds good to me then.
