### ISSUE TITLE
Unknown

### ISSUE THREAD

**Issue by MichaelHinrichs** [SteamDatabase/FileDetectionRuleSets#703]
### Some reference to the engine, such as the developer site or a wikipedia article.

N/A

### SteamDB links

https://steamdb.info/app/2723140/
https://steamdb.info/app/1679070/
https://steamdb.info/app/529720/
https://steamdb.info/app/1806840/
https://steamdb.info/app/2394810/
https://steamdb.info/app/1487320/
https://steamdb.info/app/1482770/
https://steamdb.info/app/380840/
https://steamdb.info/app/1679530/
https://steamdb.info/app/47410/
https://steamdb.info/app/1577700/
https://steamdb.info/app/675870/
https://steamdb.info/app/437730/
https://steamdb.info/app/1373350/
https://steamdb.info/app/1813730/
https://steamdb.info/app/208030/
https://steamdb.info/app/1079810/
https://steamdb.info/app/1539770/
https://steamdb.info/app/1377350/
https://steamdb.info/app/470040/
https://steamdb.info/app/1717290/
https://steamdb.info/app/1983060/
https://steamdb.info/app/772160/
https://steamdb.info/app/2084620/
https://steamdb.info/app/1083480/
https://steamdb.info/app/952330/
https://steamdb.info/app/2061580/
https://steamdb.info/app/1117420/
https://steamdb.info/app/2166200/
https://steamdb.info/app/1275210/
https://steamdb.info/app/710550/
https://steamdb.info/app/1782940/
https://steamdb.info/app/1213460/
https://steamdb.info/app/2333820/
https://steamdb.info/app/298180/
https://steamdb.info/app/2545810/
https://steamdb.info/app/427920/
https://steamdb.info/app/763610/
https://steamdb.info/app/1279000/
https://steamdb.info/app/1384400/
https://steamdb.info/app/713540/
https://steamdb.info/app/702150/
https://steamdb.info/app/930310/
https://steamdb.info/app/1683890/
https://steamdb.info/app/2233040/
https://steamdb.info/app/1394370/
https://steamdb.info/app/1694720/
https://steamdb.info/app/871720/

### Possible way to detect it

In FileDetector.php, if it's not any known engine.

**Comment by Lifeismana** [comment]
That's not something that will be done

**Comment by MichaelHinrichs** [comment]
Fuck you.

**Comment by SegaVillain** [comment]
Why not? How are people supposed to find undetected engines to add to this project, without this? Search for random steam IDs?

**Comment by SegaVillain** [comment]
@Lifeismana

**Comment by xPaw** [comment]
Being abusive and making alts is not the way to go.

If no engine is listed on a game page, that already tells you it's "unknown". Having every single game list an "Engine.Unknown" is not that useful.

**Comment by SonySidekick** [comment]
![no_unknown3](https://github.com/SteamDatabase/FileDetectionRuleSets/assets/164898223/e86324df-ddc3-487a-97c8-74daa382f247)
![no_unknown2](https://github.com/SteamDatabase/FileDetectionRuleSets/assets/164898223/1be64915-bb62-47a5-8fc2-92423bbc892c)
![no_unknown](https://github.com/SteamDatabase/FileDetectionRuleSets/assets/164898223/a52d0993-8486-40a9-aace-7b395f75c88e)
But i can't search for that! And stop banning me while i'm trying to negotiate with you. I'm nice to people who i like, and i like people who are cooperative. I don't like either of you. I'll be nice if you unban my main, and stop rejecting my pull requests for no good reason. I want to contribute to this project, and i get pissed when you make it hard for me. Making it more difficult in not the solution. Please, just let me work.

**Comment by xPaw** [comment]
You may be misunderstanding what this project is for. We're not aiming to cover every single game, but rather cover most used tech (in descending order if you want). Spamming us with PRs for tech that is used by less than 10 games is time consuming to review, and it increases the runtime of the detector. And a lot of your PRs are still open.
