### ISSUE TITLE
OGRE

### ISSUE THREAD

**Issue by mastan-rus** [SteamDatabase/FileDetectionRuleSets#71]
### Some reference to the engine, such as the developer site or a wikipedia article.

https://www.ogre3d.org/
https://en.wikipedia.org/wiki/OGRE

### SteamDB links

https://steamdb.info/app/200710/
https://steamdb.info/app/288750/
https://steamdb.info/app/270150/
https://steamdb.info/app/910830/
https://steamdb.info/app/404680/
https://steamdb.info/app/233860/
https://steamdb.info/app/23460/
https://steamdb.info/app/215160/
https://steamdb.info/app/339570/

### Possible way to detect it

Windows:
OgreMain.dll
OgreMain_x64.dll

Linux: 
libOgreMain-1.6.5.so (https://steamdb.info/depot/339574/)
libOgreMain.so.1.7.2 (https://steamdb.info/depot/248453/)
libOgreMain.so.1  (https://steamdb.info/depot/200715/)

OS X:
Universal solution is not found. Some games have "Ogre.framework" folder:
```
Hotel - Collector's Edition.app/Contents/Frameworks/Ogre.framework
Book of Unwritten Tales.app/Contents/Frameworks/Ogre.framework
enemy.app/Contents/Frameworks/Ogre.framework
```

Other files that potentially could be checked:
```
Torchlight2.app/Contents/Frameworks/libOgre.1.dylib
enemy.app/Contents/Resources/libOgreNewt.dylib
Hotel - Collector's Edition.app/Contents/Resources/lib/python2.5/lib-dynload/ogremac/renderer/OGRE/_ogre_.so
```

Suggested rules:
```
Ogre[] = (?:^|/)OgreMain(?:_x64)?\.dll$
Ogre[] = (?:^|/)libOgreMain
Ogre[] = (?:^|/)Ogre.framework$
```

**Comment by xPaw** [comment]
Briefly checked results, doesn't seem like we need to match linux or osx.

Can you make a PR that just has the dll rule? That should cover everything.
