### ISSUE TITLE
Saboteur, false positive for Godot

### ISSUE THREAD

**Issue by akien-mga** [SteamDatabase/FileDetectionRuleSets#727]
### SteamDB link to the game

https://steamdb.info/app/24880

### What is it being detected as and what should it be detected as? Any other information?

It's detected as using Godot due to the Godot heuristics being basically `<SomeName>.exe` found together with `<SomeName.pck>`, which is a match for Saboteur: https://steamdb.info/depot/24881/

![image](https://github.com/SteamDatabase/FileDetectionRuleSets/assets/4701338/fcd494de-2446-4cfc-8e54-8b75a574381d)

The Godot heuristics could possibly be changed to ensure that those two files are found in the same folder, which would exclude this.

But I'd like to review the list of positives that may be removed this way, to confirm whether they're all not using Godot.
It's technically possible to have the .pck in a different folder than the executable, as the executable will look both in its own folder and in the current working directory. And the path to the main pack can be overridden on the command line with `--main-pack path/to/file.pck`.

Otherwise, given that this is the only false positive I know of together with #30, I'm still in favor of just hardcoding those two as not-positive for Godot despite matching the heuristics (we can likely get Saboteur fixed as discussed above, but Evochron Mercenary is trickier as discussed there).

**Comment by Lifeismana** [comment]
Making sure that those 2 files are found in the same folder should indeed work
The only issue exeption to this "rule" seems to be MacOS apps
 executable is in `*insert app name*.app/Contents/MacOS/*insert app name*`
 while the pck is in `*insert app name*.app/Contents/Resources/*insert app name*.pck`
 but i doubt not detecting macos app is a problem, assuming there's no app that only ship a macos version
