### ISSUE TITLE
False Negative, Nuri VR - Coding

### ISSUE THREAD

**Issue by MichaelHinrichs** [SteamDatabase/FileDetectionRuleSets#788]
### SteamDB link to the game

https://steamdb.info/app/1448300

### What should it be detected as?

Unity

**Comment by diedyesterdaywastaken** [comment]
not going to lie, i dont think this is the compiled game 😭 they dont even have an exe for that matter

**Comment by diedyesterdaywastaken** [comment]
![image](https://github.com/SteamDatabase/FileDetectionRuleSets/assets/164639073/b738f3c8-6d8d-47eb-8d67-3bcdb06c01db)

**Comment by Lifeismana** [comment]
Not a false positive, dev delete that game's exe & files
https://steamdb.info/patchnotes/5931332/
