### ISSUE TITLE
sharpdx.org is no longer available (sharpdx is archived)

### ISSUE THREAD

**Issue by cangSDARM** [SteamDatabase/FileDetectionRuleSets#852]
### Some reference to the SDK, such as the developer site or a wikipedia article.

https://github.com/sharpdx/SharpDX

### SteamDB links

https://steamdb.info/tech/SDK/SharpDX/

**Comment by Lifeismana** [comment]
should be fixed once that commit gets pulled, thank you for that, it went under my radar
