### ISSUE TITLE
OpenAL

### ISSUE THREAD

**Issue by Faalagorn** [SteamDatabase/FileDetectionRuleSets#88]
### Some reference to the SDK, such as the developer site or a wikipedia article.

https://en.wikipedia.org/wiki/OpenAL
https://www.openal.org/

### SteamDB links

https://steamdb.info/app/41700/
https://steamdb.info/app/67000/
https://steamdb.info/app/24010/

### Possible way to detect it

* `OpenAL32.dll` or `OpenAL64.dll` in game files.
* Has OpenAL redist as a dependency, e.g. `OpenAL 2.0.7.0 Redist` here https://steamdb.info/app/24010/depots/

**Comment by ThreeDeeJay** [comment]
I'd open a PR but I'm not sure how to add more filenames in regex here https://github.com/SteamDatabase/FileDetectionRuleSets/blob/525ffba4148ac732c46b3b9560a02abbddb21300/rules.ini#L158
but there are some more files that usually determine if the came's OpenAL-capable on Windows:
`oalinst.exe` - OpenAL redistributable installer, which might not be included as a dependency.
`soft_oal.dll` - [OpenAL Soft](https://github.com/kcat/openal-soft), the newer, open-source, hardware-agnostic OpenAL implementation.
