### ISSUE TITLE
Lime / OpenFL games with lime-legacy.ndll appear to be missing

### ISSUE THREAD

**Issue by Gama11** [SteamDatabase/FileDetectionRuleSets#9]
### SteamDB link to the game

The following games are using HaxeFlixel (i.e. also OpenFL and Lime), but don't seem to be detected as anything. What they seem to have in common is that they have a lime-legacy.ndll rather than lime.ndll.

- https://steamdb.info/app/367430/
- https://steamdb.info/app/453810/
- https://steamdb.info/app/630460/

### What should it be detected as?

Lime or OpenFL

**Comment by larsiusprime** [comment]
Good catch!

**Comment by larsiusprime** [comment]
Just fixed. Should be caught by the next update.
